"""Shape detection, check visibility, probe preservation — and the catalog.

Four defects observed live, one test class each:

* **manifest detection** — `requirements-ci.txt` was not recognised, so five
  dependency checks vanished from the scorecard. The negative fixtures matter
  as much as the positive one: a prose file called `functional_requirements.txt`
  and a vendored `vendor/requirements.txt` must still NOT count. A requirements
  line gets asked two different questions — "is this file a manifest?" and "is
  this an unpinned dependency?" — and pip's own directives (`-r`, `--hash=`)
  answer them differently, so the two predicates are tested separately.
* **hidden checks** — a wrong shape reading used to *delete* checks. Every id
  must now appear in every scorecard, whatever the repo looks like.
* **clobbered probes** — `collect` reset every recorded probe to pending. It now
  preserves them, keyed on the tree hash of a clean checkout — except for the
  probes that read the WORLD rather than the tree (a CVE feed, an upstream that
  moved), which the tree hash cannot bound and which expire on age instead.
* **a lying catalog** — `references/checks.md` offered `requirements/dev.pip` as
  a file that counts (the predicate matches the basename, and `dev.pip` has no
  "requirements" in it), promised eslint to JS repos that got a bare `na`, and
  named `.venv` in a junk check that could never see one. Documentation written
  from intent instead of behaviour is the same defect as a scorecard that lies,
  one layer up, so the catalog's examples are now executed here.

Every test here was confirmed to FAIL against the code it was written for
before that code was changed; several are re-checked by neutering the fix.
"""
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import health  # noqa: E402

# Frozen. Every id health.py can emit, in every repo shape.
# Fix routes are keyed on these ids, so a rename must fail here loudly.
ALL_CHECK_IDS = {
    "sec.workflow-permissions", "sec.action-pinning", "sec.dangerous-workflow",
    "ci.timeouts", "ci.concurrency", "ci.caching", "ci.retention",
    "sec.tracked-sensitive", "sec.dep-update-config", "ci.pre-commit",
    "ci.server-side-gate", "cq.file-size", "cq.function-length",
    "hyg.tracked-junk", "hyg.large-files",
    "hyg.readme", "hyg.todo-density", "hyg.activity", "hyg.unmerged-work",
    "hyg.notebook-outputs", "ai.agents-md", "ai.verify-command", "ai.lockfiles",
    "sec.secrets-history", "sec.dep-vulns", "hyg.dep-unused", "hyg.dep-freshness",
    "sec.diff-review", "sec.sast", "cq.lint", "cq.complexity", "cq.slop",
    "sec.vendor-pins", "sec.supply-chain", "cq.ratchet", "test.suite",
    "test.runtime", "test.collection-cost", "test.parallel-safety", "ci.wall-clock",
}
DEP_CHECKS = ("sec.dep-vulns", "hyg.dep-unused", "sec.supply-chain",
              "sec.dep-update-config", "ai.lockfiles")

PROSE = """\
Functional requirements for the reporting module

Overview

The system must render a monthly summary for every active account.
Each summary shows the opening balance and the closing balance.

- Access is restricted to users with the finance role.
- Balances are rounded to two decimal places.
"""
# Prose with NO sentence in it: only a heading, a bare word and a bullet list.
# Both shapes used to parse as requirement lines — a bullet because the parser
# accepted any leading "-", a bare word because it looks like a distribution
# name — so this document read as a dependency manifest.
PROSE_BULLETS = """\
Requirements

Scope

- login
- logout
- password reset
"""
# pip-compile output: the safest requirements file there is. Every line after the
# first is a continuation carrying --hash, and every one of them used to count as
# an unpinned dependency.
HASH_PINNED = """\
#
# This file is autogenerated by pip-compile.
#
certifi==2024.2.2 \\
    --hash=sha256:0569859f95fc761b18b45ef421b1290a0f65f147e92a1e5eb3e635f9a5e4e66f \\
    --hash=sha256:dc383c07b76109f368f6106eee2b593b04a011ea4d55f652c6ca24a754d1cdd1
    # via requests
requests==2.32.3 \\
    --hash=sha256:55365417734eb18255590a9ff9eb97e9e1da868d4ccd6402399eaf68af20a760
"""
VCS_REQS = """\
git+https://github.com/foo/bar@main#egg=bar
baz @ git+https://github.com/foo/baz@1f0e3dad99908345f7439f8ffabdffc4155ffff9
"""


def git(repo, *args):
    subprocess.run(["git", "-C", str(repo), "-c", "user.email=t@t",
                    "-c", "user.name=t", *args], check=True, capture_output=True)


def make_repo(tmp_path, name, files):
    repo = tmp_path / name
    repo.mkdir(parents=True)
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    for rel, body in files.items():
        p = repo / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body)
    git(repo, "add", "-A")
    git(repo, "commit", "-qm", "init")
    return repo


def card(repo):
    return json.loads((repo / ".claude" / "health" / "scorecard.json").read_text())


def statuses(repo):
    return {c["id"]: c["status"] for c in card(repo)["checks"]}


def details(repo):
    return {c["id"]: c["detail"] for c in card(repo)["checks"]}


# ---------- the detector matches real manifests ----------

def test_requirements_ci_is_detected_and_dependency_checks_are_real(tmp_path):
    repo = make_repo(tmp_path, "reqci", {
        "requirements-ci.txt": "# pinned test env\npytest==9.1.1\nPyYAML==6.0.3\n",
        "app.py": "print('hi')\n",
    })
    shape = health.detect_shape(repo, health.tracked_files(repo))
    assert shape["manifests"] == ["requirements-ci.txt"]
    health.collect(repo)
    st = statuses(repo)
    for cid in DEP_CHECKS:
        assert st[cid] != "na", f"{cid} went n/a on a repo that HAS a manifest"


def test_the_requirement_line_parser_separates_specs_from_prose():
    """The regex alone matches functional_requirements.txt; this is what does not."""
    import shape
    for ln in ("pytest==9.1.1", "PyYAML >= 6.0", "black[jupyter]==24.1",
               "requests @ https://example.invalid/r.whl",
               "numpy; python_version < '3.12'", "django",
               "certifi==2024.2.2 \\",                      # pip-compile continuation
               "git+https://github.com/foo/bar@main#egg=bar",
               "-e git+https://github.com/foo/bar@main#egg=bar"):
        assert shape._requirement_spec(ln), f"missed a real requirement: {ln!r}"
    for ln in ("# a comment", "", "   ", "Functional requirements",
               "The system must render a monthly summary for every account.",
               "Access is restricted to users with the finance role.",
               "- Access is restricted to users with the finance role.",
               "- login", "    # via requests"):
        assert not shape._requirement_spec(ln), f"prose parsed as a requirement: {ln!r}"


def test_pip_options_are_pip_syntax_but_never_dependencies():
    """The two questions one predicate used to answer with one answer.

    A `--hash=` line proves the file is a requirements file AND is not a
    dependency; conflating those reported every hash-pinned file as unpinned.
    """
    import shape
    for ln in ("-r base.txt", "-c constraints.txt", "-e .",
               "--index-url https://example.invalid/simple",
               "--hash=sha256:0569859f95fc761b18b45ef421b1290a0f65f147e92a1e5e",
               "--require-hashes"):
        assert shape._pip_option(ln), f"missed pip syntax: {ln!r}"
        assert not shape._requirement_spec(ln), f"counted as a dependency: {ln!r}"
    for ln in ("- Access is restricted to users with the finance role.",
               "- login", "Requirements", "pytest==9.1.1"):
        assert not shape._pip_option(ln), f"prose/spec read as pip syntax: {ln!r}"


def test_pinning_needs_a_version_or_a_commit_sha():
    import shape
    for ln in ("pytest==9.1.1", "black[jupyter]===24.1",
               "requests @ https://example.invalid/r.whl",
               "baz @ git+https://github.com/foo/baz@"
               "1f0e3dad99908345f7439f8ffabdffc4155ffff9"):
        assert shape._pinned(shape._requirement_spec(ln)), f"read as unpinned: {ln!r}"
    for ln in ("PyYAML>=6.0", "django", "numpy; python_version < '3.12'",
               "git+https://github.com/foo/bar@main#egg=bar",
               "git+https://github.com/foo/bar@v1.2.3",
               "git+https://github.com/foo/bar"):
        assert not shape._pinned(shape._requirement_spec(ln)), f"read as pinned: {ln!r}"


def test_a_hash_pinned_file_is_not_reported_as_unpinned(tmp_path):
    """--hash= and -r are pip syntax, not dependencies.

    One predicate was answering two questions ("is this file a manifest?" and
    "is this line an unpinned dependency?") and gave the option lines the same
    answer to both, so the most tightly pinned file a repo can have — pip-compile
    output with hashes — reported as unpinned.
    """
    import shape as shape_mod
    repo = make_repo(tmp_path, "hashpin", {
        "requirements.txt": HASH_PINNED,
        "requirements-dev.txt": "-r requirements.txt\npytest==9.1.1\n",
        "app.py": "x = 1\n"})
    files = health.tracked_files(repo)
    detected = health.detect_shape(repo, files)["manifests"]
    assert sorted(detected) == ["requirements-dev.txt", "requirements.txt"]
    assert shape_mod.unpinned_requirements(repo, detected) == ([], [])
    health.collect(repo)
    c = next(c for c in card(repo)["checks"] if c["id"] == "ai.lockfiles")
    assert "unpinned" not in c["detail"], c["detail"]


def test_vcs_requirements_are_visible_and_a_branch_ref_is_unpinned(tmp_path):
    """A branch reference is the least pinned thing a requirements file can hold."""
    import shape as shape_mod
    repo = make_repo(tmp_path, "vcs", {
        "requirements.txt": VCS_REQS, "app.py": "x = 1\n"})
    files = health.tracked_files(repo)
    assert health.detect_shape(repo, files)["manifests"] == ["requirements.txt"]
    assert shape_mod.unpinned_requirements(repo, ["requirements.txt"]) \
        == (["requirements.txt"], [])
    # the commit-pinned sibling on its own is pinned
    (repo / "requirements.txt").write_text(VCS_REQS.splitlines()[1] + "\n")
    assert shape_mod.unpinned_requirements(repo, ["requirements.txt"]) == ([], [])


# ---------- an unopenable pyproject.toml/setup.cfg reaches `unread` too ----------

def test_an_unopenable_pyproject_toml_is_named_not_skipped(tmp_path):
    """unpinned_requirements() used to filter on `is_requirements()` FIRST — a
    basename test that pyproject.toml/setup.cfg never match — so an unopenable
    one of those never even reached `read_or_unread` and never landed in
    `unread`. `is_manifest` already counts it as a manifest when it will not
    open, so it stayed in `shape["manifests"]`, and `ai.lockfiles` read "no
    unpinned requirements found" over a file nobody had opened.
    """
    import shape as shape_mod
    repo = make_repo(tmp_path, "unreadpp", {
        "pyproject.toml": '[project]\ndependencies = ["requests>=2.0"]\n',
        "uv.lock": "# lock\n", "a.py": "x = 1\n"})
    (repo / "pyproject.toml").unlink()
    unpinned, unread = shape_mod.unpinned_requirements(
        repo, ["pyproject.toml"], health.tracked_files(repo))
    assert unpinned == [], "an unread file has no measured spec to be unpinned"
    assert unread == ["pyproject.toml"], \
        "an unopenable claimed manifest never reached `unread`"


def test_a_tracked_pyproject_unlinked_from_the_worktree_leaves_ai_lockfiles_pending(tmp_path):
    """The reproduction as found live (review): an unlinked tracked
    pyproject.toml with `requests>=2.0` beside uv.lock read `ai.lockfiles |
    pass | lockfile: uv.lock` — the sibling lockfile stood in for a manifest
    nobody had actually checked for unpinned dependencies.
    """
    repo = make_repo(tmp_path, "reppin", {
        "pyproject.toml": '[project]\ndependencies = ["requests>=2.0"]\n',
        "uv.lock": "# lock\n", "a.py": "x = 1\n"})
    (repo / "pyproject.toml").unlink()
    health.collect(repo, fresh=True)
    got = {c["id"]: c for c in card(repo)["checks"]}["ai.lockfiles"]
    assert got["status"] == "pending", got
    assert "pyproject.toml" in got["detail"], got["detail"]
    assert got.get("unread") == ["pyproject.toml"], got


def test_a_bullet_list_document_is_not_a_manifest(tmp_path):
    """The cdxgen #666 case, with no sentence in it to disqualify it cheaply."""
    repo = make_repo(tmp_path, "bullets", {
        "requirements.txt": PROSE_BULLETS, "notes.md": "# notes\n"})
    shape = health.detect_shape(repo, health.tracked_files(repo))
    assert shape["manifests"] == []


def test_prose_and_vendored_requirements_are_not_manifests(tmp_path):
    repo = make_repo(tmp_path, "negatives", {
        "functional_requirements.txt": PROSE,
        "vendor/requirements.txt": "requests==2.32.3\n",
        "third_party/pkg/requirements.txt": "requests==2.32.3\n",
        "node_modules/thing/package.json": '{"dependencies": {"x": "1"}}\n',
        "notes.md": "# notes\n",
    })
    shape = health.detect_shape(repo, health.tracked_files(repo))
    assert shape["manifests"] == []
    assert shape["locks"] == []


def test_this_repo_sees_its_own_manifest_and_no_vendored_one():
    root = Path(__file__).resolve().parents[3]
    files = health.tracked_files(root)
    assert files, f"{root} is not a git checkout"
    shape = health.detect_shape(root, files)
    # The source repo has a root requirements-ci.txt; a published copy of this
    # skill sits in a repo without one, so only the vendored-manifest check runs there.
    if (root / "requirements-ci.txt").exists():
        assert "requirements-ci.txt" in shape["manifests"]
    assert not [f for f in shape["manifests"] + shape["locks"]
                if "vendor" in Path(f).parts]


# ---------- the catalog's own examples, executed ----------
# references/checks.md is a promise about what this collector detects, and once
# one of its examples was a promise the code never kept: it offered
# `requirements/dev.pip` as a file that counts, when the predicate matches the
# BASENAME and `dev.pip` has no "requirements" in it. One example written from
# intent rather than from behaviour means the rest were never run either, so
# every filename and shape the catalog names is executed here. Add a row when
# the catalog gains an example; a doc that drifts then fails a test instead of
# misleading its reader.

CATALOG_MANIFESTS = [
    # (path, body, counts?, the catalog sentence it comes from)
    ("requirements.txt", "pytest==9.1.1\n", True, "Renovate's basename pattern"),
    ("requirements-ci.txt", "pytest==9.1.1\n", True, "…so requirements-ci.txt counts"),
    ("requirements-dev.pip", "pytest==9.1.1\n", True, "…and requirements-dev.pip counts"),
    ("requirements/dev.pip", "pytest==9.1.1\n", False, "basename-only: NOT a manifest"),
    ("sub/requirements.txt", "pytest==9.1.1\n", True, "basename, so any directory"),
    ("functional_requirements.txt", PROSE, False, "prose does not (cdxgen #666)"),
    ("package.json", '{"name": "x"}\n', True, "Dependabot's companion filenames"),
    ("setup.py", "from setuptools import setup\n", True, "…setup.py"),
    ("Pipfile", "[packages]\n", True, "…Pipfile"),
    ("setup.cfg", "[options]\ninstall_requires =\n    requests\n", True,
     "setup.cfg WITH install_requires"),
    ("setup.cfg", "[metadata]\nname = x\n", False, "…and not without it"),
    ("pyproject.toml", "[project]\nname = 'x'\n", True, "pyproject.toml with [project]"),
    ("pyproject.toml", "[tool.poetry]\nname = 'x'\n", True, "…or [tool.poetry]"),
    ("pyproject.toml", "[tool.ruff]\nline-length = 100\n", False, "…and not with neither"),
    ("vendor/pkg/requirements.txt", "pytest==9.1.1\n", False, "vendor/ is structural"),
    ("third_party/pkg/setup.py", "x = 1\n", False, "third_party/ is structural"),
    ("node_modules/pkg/package.json", '{"name": "x"}\n', False, "node_modules/ too"),
]


def test_every_manifest_example_in_the_catalog_matches_the_predicate(tmp_path):
    import shape
    for i, (rel, body, counts, why) in enumerate(CATALOG_MANIFESTS):
        repo = tmp_path / f"cat{i}"
        (repo / rel).parent.mkdir(parents=True, exist_ok=True)
        (repo / rel).write_text(body)
        assert shape.is_manifest(repo, rel) is counts, \
            f"checks.md says {rel!r} {'counts' if counts else 'does not count'} ({why})"


def test_what_actually_disqualifies_a_requirements_file(tmp_path):
    """The catalog's content-sniff sentence, run line by line.

    A `#` heading is NOT in this list on purpose: pip reads it as a comment, so
    it is stripped before the sniff and disqualifies nothing. The catalog used
    to claim it did.
    """
    import shape
    pip = "pytest==9.1.1\n"
    cases = {
        "The system must render a monthly summary.": False,   # a sentence
        "- login": False,                                     # a markdown bullet
        "# Requirements Document": True,                      # a comment to pip
        "    # via requests": True,                           # pip-compile's own
    }
    for i, (line, still_counts) in enumerate(cases.items()):
        repo = tmp_path / f"sniff{i}"
        repo.mkdir()
        (repo / "requirements.txt").write_text(pip + line + "\n")
        assert shape.is_requirements(repo, "requirements.txt") is still_counts, \
            f"{line!r}: expected the file to {'still count' if still_counts else 'be rejected'}"


def test_a_javascript_repo_is_offered_the_linter_the_catalog_promises(tmp_path):
    """checks.md promises eslint for JS repos, and semgrep that "covers TS too".

    A pure-TS repo read `na — no first-party .py files tracked` for both, so the
    lint and SAST layers went quiet on a repo that has plenty to lint. A check
    that says n/a when a tool exists for it is the shrinking scorecard again,
    one layer down.
    """
    repo = make_repo(tmp_path, "jsonly", {
        "package.json": '{"name": "x", "scripts": {"test": "jest"}}\n',
        "src/app.ts": "export const a = 1;\n"})
    health.collect(repo)
    st, det = statuses(repo), details(repo)
    assert st["cq.lint"] == "pending", f"cq.lint: {det['cq.lint']}"
    assert "eslint" in det["cq.lint"]
    assert st["sec.sast"] == "pending", f"sec.sast: {det['sec.sast']}"
    assert "semgrep" in det["sec.sast"]
    # Ruff-only rule sets stay n/a — the catalog promises those to Python only.
    assert st["cq.complexity"] == "na" and st["cq.slop"] == "na"


def test_a_repo_with_no_code_at_all_still_names_what_was_looked_for(tmp_path):
    repo = make_repo(tmp_path, "nocode", {"notes.md": "# notes\n"})
    health.collect(repo)
    det = details(repo)
    assert statuses(repo)["cq.lint"] == "na"
    assert ".py" in det["cq.lint"] and ".ts" in det["cq.lint"]


def test_tracked_junk_is_found_at_any_depth_and_inside_a_dot_directory(tmp_path):
    """The catalog names `.venv` and `node_modules`; both used to be invisible.

    `.venv/` never matched because the shared "is this our source" predicate
    drops every dot-directory, and a nested `web/node_modules/` never matched
    because the test was anchored at the repo root. The scorecard therefore
    read "no venv/node_modules/pyc tracked" over a tracked virtualenv.
    """
    repo = make_repo(tmp_path, "junkdepth", {
        "app.py": "x = 1\n",
        ".venv/lib/site.py": "x = 1\n",
        "web/node_modules/pkg/index.js": "x\n",
        "sub/dist/out.js": "x\n"})
    health.collect(repo)
    c = next(c for c in card(repo)["checks"] if c["id"] == "hyg.tracked-junk")
    assert c["status"] == "warn"
    for f in (".venv/lib/site.py", "web/node_modules/pkg/index.js", "sub/dist/out.js"):
        assert f in c["detail"], f"{f} not reported: {c['detail']}"
    assert "app.py" not in c["detail"]


def test_the_repos_own_excludes_still_silence_junk(tmp_path):
    """The widened match must not out-shout the repo's own quality ratchet."""
    repo = make_repo(tmp_path, "junkexcl", {
        "pyproject.toml": "[project]\nname = 'x'\n\n[tool.claude-quality]\nexclude = ['fixtures']\n",
        "fixtures/node_modules/pkg/index.js": "x\n"})
    health.collect(repo)
    c = next(c for c in card(repo)["checks"] if c["id"] == "hyg.tracked-junk")
    assert c["status"] == "pass", c["detail"]


# ---------- no check is ever hidden ----------

def test_every_check_id_is_present_in_every_repo_shape(tmp_path):
    shapes = {
        "bare": make_repo(tmp_path, "bare", {"notes.md": "# notes\n"}),
        "reqs": make_repo(tmp_path, "reqs", {
            "requirements-ci.txt": "pytest==9.1.1\n", "app.py": "x = 1\n"}),
        "lock": make_repo(tmp_path, "lock", {
            "uv.lock": "version = 1\n", "notes.md": "# notes\n"}),
    }
    for name, repo in shapes.items():
        health.collect(repo)
        ids = [c["id"] for c in card(repo)["checks"]]
        assert len(ids) == len(set(ids)), f"{name}: duplicate check ids"
        assert set(ids) == ALL_CHECK_IDS, f"{name}: check set differs"


def test_function_length_never_reports_clean_over_a_file_it_could_not_read(tmp_path):
    """A file that does not parse was NOT measured, and must not read as measured.

    Found in this check's own end-to-end run: the fixture was accidentally invalid
    Python, `ast.parse` raised, the file was skipped and the scorecard said
    "pass — no function over 100 lines" over a tree the check never read. That is
    the exact defect this whole skill exists to catch, produced by the check
    written to close a coverage gap.
    """
    repo = make_repo(tmp_path, "unparseable", {"src/broken.py": "def oops(:\n",
                                               "src/ok.py": "def small():\n    return 1\n"})
    health.collect(repo)
    c = next(c for c in card(repo)["checks"] if c["id"] == "cq.function-length")
    assert c["status"] == "warn", c["detail"]
    assert "src/broken.py" in c["detail"] and "NOT measured" in c["detail"]


def test_an_unmeasured_file_is_named_even_when_there_IS_a_finding(tmp_path):
    """The note was appended on the NO-FINDINGS branch only.

    So a repo with one long function AND one unparseable file reported the long
    function and never said a file had been skipped — the finding masked the gap.
    Caught by review, in the check written to stop exactly this: the
    previous test covers the clean branch, and the fix went in on that branch
    alone. A point-fix that leaves its sibling path open, one more time.
    """
    long_fn = "def big():\n" + "    x = 1\n" * 120
    repo = make_repo(tmp_path, "both", {"src/broken.py": "def oops(:\n",
                                        "src/long.py": long_fn})
    health.collect(repo)
    c = next(c for c in card(repo)["checks"] if c["id"] == "cq.function-length")
    assert c["status"] == "warn", c["detail"]
    assert "src/long.py" in c["detail"], "the finding must still be reported"
    assert "src/broken.py" in c["detail"] and "NOT measured" in c["detail"], (
        "a file that was never read must be named even when a finding exists")


def test_every_na_states_what_was_measured(tmp_path):
    repo = make_repo(tmp_path, "bare2", {"notes.md": "# notes\n"})
    health.collect(repo)
    for c in card(repo)["checks"]:
        if c["status"] == "na":
            assert len(c["detail"].split()) >= 3, f"{c['id']}: bare n/a reason"
    det = details(repo)
    assert "requirements" in det["sec.dep-vulns"]
    assert "no test suite" in det["test.suite"]


def test_lockfile_without_a_manifest_is_a_warning_not_silence(tmp_path):
    repo = make_repo(tmp_path, "lonelock", {
        "uv.lock": "version = 1\n", "notes.md": "# notes\n"})
    health.collect(repo)
    c = next(c for c in card(repo)["checks"] if c["id"] == "ai.lockfiles")
    assert c["status"] == "warn"
    assert "lock" in c["detail"].lower()


def test_set_result_names_the_known_ids_on_an_unknown_one(tmp_path, capsys):
    repo = make_repo(tmp_path, "ids", {"notes.md": "# notes\n"})
    health.collect(repo)
    try:
        health.set_result(repo, "sec.no-such-check", "pass", "")
    except SystemExit as e:
        msg = str(e)
    else:
        raise AssertionError("unknown id did not exit")
    assert "sec.no-such-check" in msg and "sec.secrets-history" in msg


# ---------- collect preserves recorded probes ----------

def _record(repo):
    health.collect(repo)
    assert statuses(repo)["sec.diff-review"] == "pending"
    health.set_result(repo, "sec.diff-review", "pass", "/security-review: 0 findings")


def probe_repo(tmp_path, name):
    return make_repo(tmp_path, name, {"app.py": "x = 1\n", "notes.md": "# n\n"})


def test_rerun_on_an_identical_clean_tree_preserves_the_recorded_probe(tmp_path):
    repo = probe_repo(tmp_path, "keep")
    _record(repo)
    health.collect(repo)
    assert statuses(repo)["sec.diff-review"] == "pass"
    assert "0 findings" in details(repo)["sec.diff-review"]


def test_amend_with_an_identical_tree_still_preserves(tmp_path):
    repo = probe_repo(tmp_path, "amend")
    _record(repo)
    git(repo, "commit", "-q", "--amend", "-m", "reworded")   # same tree, new HEAD
    health.collect(repo)
    assert statuses(repo)["sec.diff-review"] == "pass"


def test_a_dirty_tree_never_preserves(tmp_path):
    repo = probe_repo(tmp_path, "dirty")
    _record(repo)
    (repo / "app.py").write_text("x = 2\n")
    health.collect(repo)
    assert statuses(repo)["sec.diff-review"] == "pending"


def test_a_changed_tree_never_preserves(tmp_path):
    repo = probe_repo(tmp_path, "moved")
    _record(repo)
    (repo / "app.py").write_text("x = 2\n")
    git(repo, "add", "-A")
    git(repo, "commit", "-qm", "change")
    health.collect(repo)
    assert statuses(repo)["sec.diff-review"] == "pending"


def test_a_sentinel_or_missing_key_never_preserves(tmp_path):
    repo = probe_repo(tmp_path, "sentinel")
    _record(repo)
    for bogus in ("?", "", None):
        c = card(repo)
        if bogus is None:
            c.pop("tree", None)
        else:
            c["tree"] = bogus
        health.save_card(repo, c)
        health.collect(repo)
        assert statuses(repo)["sec.diff-review"] == "pending", f"preserved on {bogus!r}"
        health.set_result(repo, "sec.diff-review", "pass", "recorded again")
    assert health.recorded_probes(repo, "") == {}


def test_a_tracked_scorecard_does_not_make_its_own_tree_dirty(tmp_path):
    """This repo TRACKS .claude/health/scorecard.json.

    Writing it is the act of measuring, so it must not count as a change to the
    code being measured — otherwise preservation can never fire in the one repo
    the defect was observed in. It is also the only case that produces a
    porcelain line beginning " M ", whose leading space run() strips: the first
    fix parsed those columns by offset and worked on every fixture (all of which
    had an UNtracked "?? " line) while failing on the real repo.
    """
    repo = probe_repo(tmp_path, "tracked")
    health.collect(repo)
    git(repo, "add", "-f", ".claude/health/scorecard.json")
    git(repo, "commit", "-qm", "track the scorecard")
    clean = health.tree_key(repo)
    assert len(clean) == 40, "a tracked scorecard left the tree looking dirty"
    health.collect(repo)
    health.set_result(repo, "sec.diff-review", "pass", "/security-review: 0 findings")
    assert health.tree_key(repo) == clean, "rewriting the scorecard dirtied the tree"
    health.collect(repo)
    assert statuses(repo)["sec.diff-review"] == "pass"


def test_a_world_dependent_probe_expires_while_a_tree_one_does_not(tmp_path):
    """The tree hash is the right key only for probes that read the tree.

    `sec.dep-vulns` reads a CVE feed and `sec.vendor-pins` exists to notice that
    UPSTREAM moved — and upstream moving never changes a byte here. Keyed on the
    tree alone, a month-old pip-audit pass gets republished under today's date
    and today's score.
    """
    repo = make_repo(tmp_path, "world", {
        "requirements.txt": "pytest==9.1.1\n", "app.py": "x = 1\n"})
    health.collect(repo)
    assert statuses(repo)["sec.dep-vulns"] == "pending"
    health.set_result(repo, "sec.dep-vulns", "pass", "pip-audit: 0 vulnerabilities")
    health.set_result(repo, "sec.diff-review", "pass", "/security-review: 0 findings")
    health.collect(repo)                      # recorded today: both still hold
    assert statuses(repo)["sec.dep-vulns"] == "pass"
    assert statuses(repo)["sec.diff-review"] == "pass"

    c = card(repo)                            # same tree, a much older world
    for chk in c["checks"]:
        if chk.get("recorded"):
            chk["recorded"] = "2020-01-01"
    health.save_card(repo, c)
    health.collect(repo)
    st = statuses(repo)
    assert st["sec.dep-vulns"] == "pending", "a 2020 pip-audit was republished as today's"
    assert st["sec.diff-review"] == "pass", "a tree-dependent probe must not expire"


def test_every_world_probe_id_is_really_emitted(tmp_path):
    """An id list in one file, the probes in another: bind them or they drift.

    A renamed probe would otherwise unbind itself from the age bound silently,
    and the result — a stale pass republished as today's — looks exactly like a
    real pass.
    """
    import probes
    repo = make_repo(tmp_path, "worldids", {
        "requirements.txt": "pytest==9.1.1\n", "app.py": "x = 1\n"})
    health.collect(repo)
    emitted = {c["id"] for c in card(repo)["checks"]}
    assert probes.WORLD_PROBES <= emitted, probes.WORLD_PROBES - emitted
    assert probes.WORLD_PROBES <= ALL_CHECK_IDS


def test_a_world_probe_with_no_recording_date_is_not_preserved(tmp_path):
    """A card written before the stamp existed cannot prove its probe was recent."""
    repo = make_repo(tmp_path, "undated", {
        "requirements.txt": "pytest==9.1.1\n", "app.py": "x = 1\n"})
    health.collect(repo)
    health.set_result(repo, "sec.dep-vulns", "pass", "pip-audit: 0 vulnerabilities")
    c = card(repo)
    for chk in c["checks"]:
        chk.pop("recorded", None)
    health.save_card(repo, c)
    health.collect(repo)
    assert statuses(repo)["sec.dep-vulns"] == "pending"


def test_fresh_forces_a_full_reset(tmp_path):
    repo = probe_repo(tmp_path, "fresh")
    _record(repo)
    health.collect(repo, fresh=True)
    assert statuses(repo)["sec.diff-review"] == "pending"


def test_deterministic_checks_are_recomputed_not_preserved(tmp_path):
    repo = probe_repo(tmp_path, "recompute")
    health.collect(repo)
    health.set_result(repo, "hyg.readme", "pass", "hand-forced")
    health.collect(repo)
    assert statuses(repo)["hyg.readme"] == "warn"   # no README: recomputed
