#!/usr/bin/env python3
"""Render Codex's global instructions from the Claude harness rules.

Claude Code reads ~/.claude/CLAUDE.md and ~/.claude/rules/*.md. Codex reads one
global file, ~/.codex/AGENTS.md, and cannot follow @imports. So this script
renders CLAUDE.md + rules/*.md into codex/global-instructions.md (committed);
the ordinary deploy moves it to ~/.claude/codex/, and ~/.codex/AGENTS.md is a
symlink to it. One source, no hand-kept twin to drift.

Markers in CLAUDE.md (each on a line of its own; anything else is plain text):
    <!-- claude-only --> ... <!-- /claude-only -->   dropped from the render
    <!-- BEGIN ROUTING ... --> ... <!-- END ROUTING -->  dropped (Claude tier table)
    <!-- codex-only                                  inner lines rendered;
    ...                                              Claude strips the whole
    -->                                              block-level comment
Unbalanced or nested markers fail closed.

Usage:
    render-codex-instructions.py           write codex/global-instructions.md
    render-codex-instructions.py --check   exit 1 if the committed file is stale
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = Path("codex/global-instructions.md")

BANNER = (
    "# Codex - User Configuration\n\n"
    "GENERATED from the source repo's CLAUDE.md and rules/*.md by "
    "scripts/render-codex-instructions.py. Do not edit this file: edit the source "
    "and re-run the script.\n"
)

OPEN_CLAUDE = re.compile(r"^<!-- claude-only -->$")
CLOSE_CLAUDE = re.compile(r"^<!-- /claude-only -->$")
OPEN_ROUTING = re.compile(r"^<!-- BEGIN ROUTING\b.*-->$")
CLOSE_ROUTING = re.compile(r"^<!-- END ROUTING -->$")
OPEN_CODEX = re.compile(r"^<!-- codex-only$")
CLOSE_CODEX = re.compile(r"^-->$")
ANY_MARKER = re.compile(r"^<!-- (/?claude-only|codex-only|BEGIN ROUTING|END ROUTING)\b")


class RenderError(Exception):
    pass


def render_claude_md(text: str) -> str:
    out: list[str] = []
    mode = None  # None | "drop" | "codex"
    closer = None
    for n, line in enumerate(text.splitlines(), 1):
        s = line.strip()
        if mode is None:
            if OPEN_CLAUDE.match(s):
                mode, closer = "drop", CLOSE_CLAUDE
            elif OPEN_ROUTING.match(s):
                mode, closer = "drop", CLOSE_ROUTING
            elif OPEN_CODEX.match(s):
                mode, closer = "codex", CLOSE_CODEX
            elif ANY_MARKER.match(s):
                raise RenderError(f"line {n}: closing marker with no opener: {s}")
            else:
                out.append(line)
            continue
        if closer.match(s):
            mode = closer = None
        elif ANY_MARKER.match(s):
            raise RenderError(f"line {n}: nested marker inside an open block: {s}")
        elif mode == "codex":
            out.append(line)
    if mode is not None:
        raise RenderError(f"unclosed {mode} block at end of file")
    lines = out[1:] if out and out[0].startswith("# ") else out  # BANNER replaces the H1
    body = "\n".join(lines)
    body = body.replace("(why: docs/", "(why: ~/.claude/docs/")
    return re.sub(r"\n{3,}", "\n\n", body).strip() + "\n"


def render(repo: Path) -> str:
    parts = [BANNER, render_claude_md((repo / "CLAUDE.md").read_text())]
    parts += [p.read_text().strip() + "\n" for p in sorted((repo / "rules").glob("*.md"))]
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed render is stale")
    ap.add_argument("--repo", type=Path, default=REPO)
    args = ap.parse_args(argv)
    try:
        want = render(args.repo)
    except RenderError as e:
        print(f"render-codex-instructions: CLAUDE.md {e}", file=sys.stderr)
        return 2
    target = args.repo / OUT
    if args.check:
        if not target.exists() or target.read_text() != want:
            print(f"render-codex-instructions: {OUT} is stale. Run "
                  "`python3 scripts/render-codex-instructions.py` and `git add "
                  f"{OUT}`.", file=sys.stderr)
            return 1
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(want)
    print(f"wrote {OUT} ({len(want.encode())} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
